Repository Team-MOISAM/moisam-client, pull requests merged in 2025-04, with the labels that each got.

#2 Feat(1) : 카카오맵 API 활용 컴포넌트 구현
  .gitignore
  package.json
  pnpm-lock.yaml
  src/app/main.tsx
  src/features/mapView/index.ts
  src/features/mapView/ui/KakaoMapView.tsx
  src/features/mapView/ui/MapMarker.tsx
  src/features/mapView/ui/index.ts
  src/pages/MapViewPage.tsx
  src/shared/model/index.ts
  src/shared/model/kakao.maps.d.ts
  src/shared/model/mocks/mockLocationData.ts
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
Labels: ✨ feature

#7 [feat] : main 페이지 ui 구현 및 공통 버튼 구현
  public/icon/kakao.svg
  public/icon/logo.svg
  src/features/main/ui/KakaoLogin.tsx
  src/features/main/ui/index.ts
  src/pages/MainPage.tsx
  src/shared/ui/Button.tsx
  src/shared/ui/index.ts
  tailwind.config.cjs
Labels: ✨ feature, 💄 ui

#11 [feat] : 공통 헤더 구현
  public/icon/back.svg
  public/icon/close.svg
  src/shared/ui/BackHeader.tsx
  src/shared/ui/CloseHeader.tsx
  src/shared/ui/PlainHeader.tsx
  src/shared/ui/index.ts
Labels: ✨ feature, 💄 ui

#9 [feat] : HI 페이지 UI 구현
  public/icon/arrow.svg
  public/icon/check.svg
  public/icon/pin.svg
  public/icon/review.svg
  public/image/banner.png
  src/app/routes/routes.tsx
  src/features/history/ui/Banner.tsx
  src/features/history/ui/Chip.tsx
  src/features/history/ui/Empty.tsx
  src/features/history/ui/GroupCard.tsx
  src/features/history/ui/Header.tsx
  src/features/history/ui/index.ts
  src/pages/HistoryPage.tsx
  src/shared/model/index.ts
  src/shared/model/mocks/mockListData.ts
  tailwind.config.cjs
Labels: ✨ feature, 💄 ui

#12 [refactor] : index 파일 추가
  src/features/history/ui/index.ts
Labels: 🛠 refactor

#20 [feat] : Find 페이지 UI 구현
  package.json
  pnpm-lock.yaml
  public/icon/location.svg
  public/icon/search.svg
  src/features/find/ui/FindContainer.tsx
  src/features/find/ui/GetLocationButton.tsx
  src/features/find/ui/LocationStep.tsx
  src/features/find/ui/NameStep.tsx
  src/features/find/ui/index.ts
  src/features/history/ui/Banner.tsx
  src/features/history/ui/Chip.tsx
  src/features/history/ui/Empty.tsx
  src/features/history/ui/GroupCard.tsx
  src/features/history/ui/Header.tsx
  src/features/main/ui/KakaoLogin.tsx
  src/features/mapView/index.ts
  src/features/mapView/ui/KakaoMapView.tsx
  src/features/mapView/ui/MapMarker.tsx
  src/pages/FindPage.tsx
  src/pages/HistoryPage.tsx
  src/pages/MainPage.tsx
  src/pages/MapViewPage.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/useValidation.ts
  src/shared/index.ts
  src/shared/model/index.ts
  src/shared/model/mocks/mockSearchData.ts
  src/shared/stores/index.ts
  src/shared/stores/useFindStore.ts
  src/shared/ui/InputField.tsx
  src/shared/ui/LocationCard.tsx
  src/shared/ui/PlainHeader.tsx
  src/shared/ui/index.ts
  src/shared/utils/index.ts
  src/shared/utils/validateName.ts
  tailwind.config.cjs
Labels: ✨ feature, 💄 ui

#14 [feat] : MY 페이지 UI 구현
  public/icon/edit.svg
  public/icon/logout.svg
  public/icon/rightArrow.svg
  src/app/routes/routes.tsx
  src/features/history/ui/Header.tsx
  src/features/main/ui/KakaoLogin.tsx
  src/features/my/ui/Logout.tsx
  src/features/my/ui/Menu.tsx
  src/features/my/ui/Profile.tsx
  src/features/my/ui/index.tsx
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
  src/shared/ui/Button.tsx
Labels: ✨ feature, 💄 ui

#16 [feat] : Review 페이지 및 방문하지 않은 경우의 페이지 UI 구현
  public/icon/checkBlue.svg
  public/icon/people.svg
  public/icon/plug.svg
  public/icon/seat.svg
  public/icon/seatGray.svg
  public/icon/star.svg
  src/app/routes/routes.tsx
  src/features/history/ui/Chip.tsx
  src/features/history/ui/GroupCard.tsx
  src/features/my/ui/Menu.tsx
  src/features/notVisited/ui/FirstStep.tsx
  src/features/notVisited/ui/ScoreSelector.tsx
  src/features/notVisited/ui/SecondStep.tsx
  src/features/review/ui/SmallButton.tsx
  src/features/review/ui/Title.tsx
  src/features/review/ui/index.ts
  src/pages/MyPage.tsx
  src/pages/NotVisitedPage.tsx
  src/pages/ReviewPage.tsx
  src/shared/model/mocks/mockPlaceList.ts
  src/shared/ui/BackHeader.tsx
  src/shared/ui/PlaceCard.tsx
  src/shared/ui/PlaceChip.tsx
  src/shared/ui/StepIndicator.tsx
  src/shared/ui/index.ts
Labels: ✨ feature, 💄 ui
