Repository Team-MOISAM/moisam-client, pull requests merged in 2025-09, with the labels that each got.

#222 [SPOT-180] : gtag 유틸리티 설정 및 이벤트 추가
  src/features/detail/ui/PlaceButton.tsx
  src/features/detail/ui/PlaceInfo.tsx
  src/features/find/ui/EventNameStep.tsx
  src/features/find/ui/GetLocationButton.tsx
  src/features/find/ui/LocationStep.tsx
  src/features/find/ui/NameStep.tsx
  src/features/history/ui/Chip.tsx
  src/features/history/ui/GroupCard.tsx
  src/features/mapView/ui/bottomsheets/detailContents/MapModal.tsx
  src/features/mapView/ui/bottomsheets/detailContents/TransferDetail.tsx
  src/features/mapView/ui/bottomsheets/durationBottomsheet/BottomSheetContent.tsx
  src/features/mapView/ui/bottomsheets/durationBottomsheet/GroupInfo.tsx
  src/features/my/ui/DeleteAccountModal.tsx
  src/features/my/ui/Logout.tsx
  src/features/place/ui/RecommendList.tsx
  src/pages/DetailPage.tsx
  src/pages/MainPage.tsx
  src/pages/MapViewPage.tsx
  src/pages/NotVisitedPage.tsx
  src/pages/PlacePage.tsx
  src/pages/VisitedPage.tsx
  src/shared/ui/PointChip.tsx
  src/shared/ui/PolicyBottomSheet.tsx
  src/shared/ui/ShareModal.tsx
  src/shared/utils/gtag.ts
  src/shared/utils/index.ts
  src/shared/utils/kakaoLogin.ts
  src/shared/utils/kakaoShare.ts
  src/vite-env.d.ts
Labels: ✨ feature

#223 [MOISAM-202] : 모임 확정 api 수정
  src/features/detail/hooks/useSetPlace.ts
  src/features/detail/service/api.ts
Labels: ⚙ api

#226 [MOISAM-212] : 리뷰 재진입 로직 제거
  src/pages/HistoryPage.tsx
Labels: 🔨 fix

#227 [MOISAM-213] : HI 1명일 경우 역 제거
  src/features/history/ui/GroupCard.tsx
Labels: 🔨 fix
