Repository Team-MOISAM/moisam-client, pull requests merged in 2025-08, with the labels that each got.

#211 [SPOT-62] : 랜딩 페이지 구현
  src/assets/icon/blueTail.svg
  src/assets/icon/instagram.svg
  src/assets/icon/leftTail.svg
  src/assets/icon/logoWhite.svg
  src/assets/icon/rightTail.svg
  src/assets/icon/whiteTail.svg
  src/assets/image/car.webp
  src/assets/image/footer.webp
  src/assets/image/intro.webp
  src/assets/image/invite.webp
  src/assets/image/main.webp
  src/assets/image/meetPoint.webp
  src/assets/image/place.webp
  src/assets/image/transfer.webp
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/features/detail/ui/PlaceInfo.tsx
  src/features/history/ui/GroupCard.tsx
  src/features/main/ui/Bubble.tsx
  src/features/main/ui/Footer.tsx
  src/features/main/ui/IntroSection.tsx
  src/features/main/ui/InviteBubble.tsx
  src/features/main/ui/InviteSection.tsx
  src/features/main/ui/KakaoLogin.tsx
  src/features/main/ui/MeetPointSection.tsx
  src/features/main/ui/PathSection.tsx
  src/features/main/ui/PlaceSection.tsx
  src/features/main/ui/Title.tsx
  src/features/main/ui/index.ts
  src/features/mapView/config/subwayLine.ts
  src/features/mapView/ui/bottomsheets/detailContents/BusChip.tsx
  src/features/mapView/ui/bottomsheets/detailContents/BusPath.tsx
  src/features/mapView/ui/bottomsheets/detailContents/MapModal.tsx
  src/features/mapView/ui/bottomsheets/detailContents/Path.tsx
  src/features/mapView/ui/common/LoginModal.tsx
  src/pages/MainPage.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/useScrollAnimation.ts
  src/shared/ui/AnimatedSection.tsx
  src/shared/ui/InputField.tsx
  src/shared/ui/MeetPointCard.tsx
  src/shared/ui/PlaceCard.tsx
  src/shared/ui/PlaceChip.tsx
  src/shared/ui/ShareModal.tsx
  src/shared/ui/index.ts
  src/widgets/headers/index.ts
  src/widgets/headers/ui/LoginHeader.tsx
  tailwind.config.cjs
Labels: ✨ feature, 💄 ui

#213 [SPOT-62] : 랜딩 페이지 이미지 수정
  src/assets/icon/footerIcon.svg
  src/assets/image/footer.webp
  src/assets/image/footerImg.webp
  src/features/main/ui/Footer.tsx
  src/features/main/ui/InviteSection.tsx
Labels: 🔨 fix, 💄 ui

#217 [SPOT-171] : 모임 수정 디폴트값 및 find 리디렉션 수정
  src/features/find/ui/DatePicker.tsx
  src/features/find/ui/EventNameStep.tsx
  src/features/find/ui/FindContainer.tsx
  src/features/find/ui/TimePicker.tsx
  src/features/mapView/ui/common/LoginModal.tsx
  src/pages/KakaoCallbackPage.tsx
Labels: 🐞 bug, 🔨 fix

#219 [SPOT-173] : 0분일 때 오류 대응 구현
  src/assets/icon/warning.svg
  src/features/mapView/ui/bottomsheets/durationBottomsheet/UserCard.tsx
Labels: ✨ feature, 💄 ui
