Repository Team-MOISAM/moisam-client, pull requests merged in 2025-05, with the labels that each got.

#21 [feat] : DE 페이지 UI 구현
  public/icon/kakaoMap.svg
  public/icon/naverMap.svg
  public/icon/pinBlue.svg
  public/icon/plug.svg
  public/icon/seat.svg
  public/icon/star.svg
  public/icon/time.svg
  src/features/detail/config/ProgressType.ts
  src/features/detail/config/TagTypeInfo.ts
  src/features/detail/config/index.ts
  src/features/detail/ui/Empty.tsx
  src/features/detail/ui/Photo.tsx
  src/features/detail/ui/PlaceInfo.tsx
  src/features/detail/ui/ProgressBar.tsx
  src/features/detail/ui/Review.tsx
  src/features/detail/ui/ReviewItem.tsx
  src/features/detail/ui/Tag.tsx
  src/features/detail/ui/index.ts
  src/pages/DetailPage.tsx
  tailwind.config.cjs
Labels: ✨ feature, 💄 ui

#23 [feat] : 모달 UI 구현
  index.html
  public/icon/closeGray.svg
  public/icon/kakaoShare.svg
  public/icon/linkCopy.svg
  src/features/detail/ui/PlaceModal.tsx
  src/features/detail/ui/ShareModal.tsx
  src/features/detail/ui/index.ts
  src/shared/ui/Modal.tsx
  src/shared/ui/Portal.tsx
  src/shared/ui/index.ts
Labels: ✨ feature, 💄 ui

#24 [feat] : MP페이지 1~4 구현
  public/icon/addUser.svg
  public/icon/default-profile.svg
  public/icon/drag.svg
  public/icon/meeting-spot.svg
  public/icon/polygon.svg
  public/icon/share.svg
  public/icon/transfer.svg
  public/icon/user-spot.svg
  src/app/index.css
  src/features/mapView/ui/AddMemberBottomSheet.tsx
  src/features/mapView/ui/BottomSheetContent.tsx
  src/features/mapView/ui/KakaoMapView.tsx
  src/features/mapView/ui/MapBottomSheet.tsx
  src/features/mapView/ui/MapHeader.tsx
  src/features/mapView/ui/MapMarker.tsx
  src/features/mapView/ui/MeetingMarker.tsx
  src/features/mapView/ui/UserCard.tsx
  src/features/mapView/ui/index.ts
  src/pages/MapViewPage.tsx
  src/shared/hooks/useBottomSheetDrag.ts
  src/shared/model/MapData.type.ts
  src/shared/model/index.ts
  src/shared/model/kakao.maps.d.ts
  src/shared/model/mocks/mockLocationData.ts
  src/shared/model/mocks/mockMapData.ts
  src/shared/stores/index.ts
  src/shared/stores/useMapStore.ts
  src/shared/ui/BottomSheet/BottomSheet.tsx
  src/shared/ui/BottomSheet/Content.tsx
  src/shared/ui/BottomSheet/Header.tsx
  src/shared/ui/BottomSheet/Overlay.tsx
  src/shared/ui/BottomSheet/Wrapper.tsx
  src/shared/ui/index.ts
Labels: ✨ feature, 💄 ui

#26 [feat] : PL 페이지 UI 구현
  public/icon/blueCheck.svg
  public/icon/drinking.svg
  public/icon/meeting.svg
  public/icon/study.svg
  src/features/place/ui/ConfirmedCard.tsx
  src/features/place/ui/FilterChips.tsx
  src/features/place/ui/RecommendCard.tsx
  src/features/place/ui/RecommendList.tsx
  src/features/place/ui/index.ts
  src/pages/PlacePage.tsx
  src/shared/ui/PlaceCard.tsx
Labels: ✨ feature, 💄 ui

#30 [refactor] RE 페이지 페이지 이동 수정 및 UI 수정
  src/app/routes/routes.tsx
  src/features/visited/ui/FirstStep.tsx
  src/features/visited/ui/ScoreSelector.tsx
  src/features/visited/ui/SecondStep.tsx
  src/features/visited/ui/index.ts
  src/pages/DetailPage.tsx
  src/pages/FindPage.tsx
  src/pages/HistoryPage.tsx
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
  src/pages/PlacePage.tsx
  src/pages/ReviewPage.tsx
  src/pages/VisitedPage.tsx
  tailwind.config.cjs
Labels: 🛠 refactor, 💄 ui

#32 [fix] : 스크롤과 드래그 이벤트 분리
  src/features/mapView/ui/BottomSheetContent.tsx
  src/pages/MapViewPage.tsx
  src/shared/hooks/useBottomSheetDrag.ts
Labels: ✨ feature, 🔨 fix

#34 [feat] : History 이용약관 바텀시트 UI 구현
  public/icon/checkBox.svg
  public/icon/checkBoxBlue.svg
  src/features/history/ui/CheckBox.tsx
  src/features/history/ui/Chip.tsx
  src/features/history/ui/PolicyBottomSheet.tsx
  src/features/history/ui/index.ts
  src/pages/HistoryPage.tsx
  src/shared/ui/BottomSheet/Overlay.tsx
Labels: ✨ feature, 💄 ui

#37 [feat] : 스내핑 바텀 시트 구현
  src/app/index.css
  src/features/mapView/ui/BottomSheetContent.tsx
  src/features/mapView/ui/SnapBottomSheet.tsx
  src/features/mapView/ui/index.ts
  src/pages/MapViewPage.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/useBottomSheetSnap.ts
  src/shared/model/mocks/mockMapData.ts
  src/shared/ui/SnapBottomSheet/SnapBottomSheet.tsx
  src/shared/ui/SnapBottomSheet/SnapContent.tsx
  src/shared/ui/SnapBottomSheet/SnapHeader.tsx
  src/shared/ui/SnapBottomSheet/SnapWrapper.tsx
  src/shared/ui/index.ts
Labels: ✨ feature, 🔨 fix

#40 [fix] : QA 디자인 수정 요청 사항 반영
  index.html
  public/image/banner.png
  src/app/index.css
  src/features/history/ui/Chip.tsx
  src/features/history/ui/GroupCard.tsx
  src/features/history/ui/PolicyBottomSheet.tsx
  src/features/my/ui/Menu.tsx
  src/features/my/ui/Profile.tsx
  src/features/visited/ui/SecondStep.tsx
  src/pages/HistoryPage.tsx
  src/pages/MyPage.tsx
Labels: 🔨 fix, 💄 ui

#42 [feat] : ResizeObserver 적용해 동적 높이 계산
  src/features/mapView/ui/SnapBottomSheet.tsx
  src/shared/hooks/useBottomSheetSnap.ts
  src/shared/ui/SnapBottomSheet/SnapBottomSheet.tsx
Labels: ✨ feature

#43 [feat] : mapViewDetail UI 구현
  public/icon/TMap.svg
  public/icon/bus.svg
  public/icon/car.svg
  public/icon/carGray.svg
  public/icon/end.svg
  public/icon/longPath.svg
  public/icon/middlePath.svg
  public/icon/parking.svg
  public/icon/rightArrowLine.svg
  public/icon/shortPath.svg
  public/icon/start.svg
  public/icon/subway.svg
  public/icon/subwayGray.svg
  public/icon/walk.svg
  src/features/mapView/config/subwayLine.ts
  src/features/mapView/model/index.ts
  src/features/mapView/model/transfer.ts
  src/features/mapView/ui/DetailBottomSheet/BusChip.tsx
  src/features/mapView/ui/DetailBottomSheet/BusPath.tsx
  src/features/mapView/ui/DetailBottomSheet/FixedButton.tsx
  src/features/mapView/ui/DetailBottomSheet/Path.tsx
  src/features/mapView/ui/DetailBottomSheet/SubwayPath.tsx
  src/features/mapView/ui/DetailBottomSheet/TransferDetail.tsx
  src/features/mapView/ui/DetailBottomSheet/WalkPath.tsx
  src/features/mapView/ui/DetailBottomSheet/index.ts
  src/features/mapView/ui/DetailKakaoMapView.tsx
  src/features/mapView/ui/KakaoMapView.tsx
  src/features/mapView/ui/MapBottomSheet.tsx
  src/features/mapView/ui/MapDetailBottomSheet.tsx
  src/features/mapView/ui/MapHeader.tsx
  src/features/mapView/ui/TransferDetail.tsx
  src/features/mapView/ui/index.ts
  src/pages/MapViewPage.tsx
  src/shared/hooks/useBottomSheetSnap.ts
  src/shared/model/MapData.type.ts
  src/shared/model/mocks/mockMapData.ts
  src/shared/ui/SnapBottomSheet/SnapBottomSheet.tsx
Labels: ✨ feature, 💄 ui

#46 [feat] : 카카오톡 소셜 로그인 MA 그래픽 추가
  package.json
  pnpm-lock.yaml
  public/image/main.png
  src/features/history/ui/Banner.tsx
  src/features/history/ui/Chip.tsx
  src/features/history/ui/Empty.tsx
  src/features/main/ui/KakaoLogin.tsx
  src/pages/HistoryPage.tsx
  src/pages/MainPage.tsx
  src/shared/api/api.ts
  src/shared/api/index.ts
Labels: ⚙ api, ✨ feature, 💄 ui

#48 [feat] : QA 수정 사항 반영 및 그래픽 추가
  index.html
  package.json
  pnpm-lock.yaml
  public/favicon.svg
  public/icon/afternoon.svg
  public/icon/afternoonBlue.svg
  public/icon/emptyDetail.svg
  public/icon/emptyHistory.svg
  public/icon/evening.svg
  public/icon/eveningBlue.svg
  public/icon/morning.svg
  public/icon/morningBlue.svg
  public/vite.svg
  src/features/detail/config/ProgressType.ts
  src/features/detail/ui/Empty.tsx
  src/features/detail/ui/ProgressBar.tsx
  src/features/history/ui/Chip.tsx
  src/features/history/ui/Empty.tsx
  src/features/visited/ui/FirstStep.tsx
  src/features/visited/ui/SecondStep.tsx
  src/pages/DetailPage.tsx
  src/pages/VisitedPage.tsx
  src/shared/ui/BottomSheet/BottomSheet.tsx
  src/shared/ui/BottomSheet/Wrapper.tsx
Labels: ✨ feature, 🔨 fix, 💄 ui

#49 [fix] 배포환경에서 RE 페이지 스크롤 영역 수정
  src/app/index.css
  src/pages/VisitedPage.tsx
Labels: 🔨 fix

#50 [feat] : 카카오톡 공유 및 api 연동을 위한 사전작업
  index.html
  package.json
  pnpm-lock.yaml
  src/app/App.tsx
  src/app/main.tsx
  src/features/detail/ui/ShareModal.tsx
  src/features/detail/ui/index.ts
  src/features/mapView/ui/BottomSheetContent.tsx
  src/features/mapView/ui/LoginModal.tsx
  src/features/mapView/ui/index.ts
  src/shared/model/index.ts
  src/shared/model/kakaoShare.type.ts
  src/shared/ui/Modal.tsx
  src/shared/ui/ShareModal.tsx
  src/shared/ui/index.ts
  src/shared/utils/cookie.ts
  src/shared/utils/index.ts
  src/shared/utils/kakaoShare.ts
  src/vite-env.d.ts
Labels: ✨ feature, 💄 ui

#55 [feat] 유저 정보 조회 및 약관 동의 저장 API 연결
  index.html
  src/features/history/hooks/index.ts
  src/features/history/hooks/useStoreAgreement.ts
  src/features/history/hooks/useUserInfo.ts
  src/features/history/service/api.ts
  src/features/history/service/index.ts
  src/features/history/ui/PolicyBottomSheet.tsx
  src/features/main/ui/KakaoLogin.tsx
  src/features/my/hooks/index.ts
  src/features/my/hooks/useLogout.ts
  src/features/my/service/api.ts
  src/features/my/service/index.ts
  src/features/my/ui/Logout.tsx
  src/features/my/ui/Profile.tsx
  src/pages/HistoryPage.tsx
  src/shared/stores/index.ts
  src/shared/stores/userStore.ts
  vite.config.ts
Labels: ⚙ api, ✨ feature

#53 [feat] : find페이지 api를 연동
  src/features/find/hooks/index.ts
  src/features/find/hooks/useCreateStartPoint.ts
  src/features/find/hooks/useSearch.ts
  src/features/find/model/find.type.ts
  src/features/find/model/index.ts
  src/features/find/service/api.ts
  src/features/find/service/coord2Address.ts
  src/features/find/service/index.ts
  src/features/find/ui/FindContainer.tsx
  src/features/find/ui/GetLocationButton.tsx
  src/features/find/ui/LocationStep.tsx
  src/features/find/ui/NameStep.tsx
  src/features/history/ui/Banner.tsx
  src/features/mapView/ui/BottomSheetContent.tsx
  src/features/mapView/ui/LoginModal.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/useDebounce.ts
  src/shared/hooks/useValidation.ts
  src/shared/model/index.ts
  src/shared/model/kakao.maps.d.ts
  src/shared/model/mocks/mockSearchData.ts
  src/shared/stores/index.ts
  src/shared/stores/useFindStore.ts
  src/shared/ui/LocationCard.tsx
  src/shared/utils/highlightMatchingText.tsx
  src/shared/utils/index.ts
  src/shared/utils/loadKakaoMap.ts
Labels: ⚙ api, ✨ feature

#58 [fix] : KT2 이미지 비율 수정
  src/shared/utils/kakaoShare.ts
Labels: 🔨 fix

#61 [feat] : MP 상세 경로 연결 및 대중교통 길찾기 연결
  public/icon/leftArrow.svg
  public/icon/longPath.svg
  src/features/mapView/config/subwayLine.ts
  src/features/mapView/hooks/index.ts
  src/features/mapView/hooks/useTransfer.ts
  src/features/mapView/model/index.ts
  src/features/mapView/model/openMap.type.ts
  src/features/mapView/model/transfer.ts
  src/features/mapView/model/transfer.type.ts
  src/features/mapView/service/api.ts
  src/features/mapView/ui/BackButton.tsx
  src/features/mapView/ui/BottomSheetContent.tsx
  src/features/mapView/ui/DetailBottomSheet/BusPath.tsx
  src/features/mapView/ui/DetailBottomSheet/FixedButton.tsx
  src/features/mapView/ui/DetailBottomSheet/Path.tsx
  src/features/mapView/ui/DetailBottomSheet/SubwayPath.tsx
  src/features/mapView/ui/DetailBottomSheet/TransferDetail.tsx
  src/features/mapView/ui/DetailBottomSheet/WalkPath.tsx
  src/features/mapView/ui/DetailKakaoMapView.tsx
  src/features/mapView/ui/MapDetailBottomSheet.tsx
  src/features/mapView/ui/TransferDetail.tsx
  src/features/mapView/ui/UserCard.tsx
  src/features/mapView/utils/index.ts
  src/features/mapView/utils/kakaoMap.ts
  src/features/mapView/utils/naverMap.ts
  src/features/mapView/utils/tMap.ts
  src/features/mapView/utils/useDeviceDetector.ts
  src/pages/MapViewPage.tsx
  src/shared/stores/index.ts
  src/shared/stores/useEventStore.ts
  src/shared/stores/useMapStore.ts
Labels: ⚙ api, ✨ feature, 💄 ui

#66 [fix] : 카카오 소셜 로그인 URI 수정
  src/features/main/ui/KakaoLogin.tsx
Labels: 🐞 bug, 🔨 fix

#68 [fix] : 지하철 노선명에 따른 컴포넌트 렌더링 문제 해결
  src/features/mapView/config/subwayLine.ts
  src/features/mapView/model/openMap.type.ts
  src/features/mapView/ui/DetailBottomSheet/SubwayPath.tsx
  src/features/mapView/ui/DetailBottomSheet/TransferDetail.tsx
  src/features/mapView/utils/kakaoMap.ts
  src/features/mapView/utils/naverMap.ts
  src/features/mapView/utils/tMap.ts
Labels: 🔨 fix

#69 [refactor] : FSD구조 설정 및 ui수정
  src/features/find/ui/LocationStep.tsx
  src/features/find/ui/NameStep.tsx
  src/features/history/ui/PolicyBottomSheet.tsx
  src/features/mapView/hooks/useEventInfo.ts
  src/features/mapView/ui/AddMemberBottomSheet.tsx
  src/features/mapView/ui/TooCloseSheet.tsx
  src/features/mapView/ui/index.ts
  src/pages/MapViewPage.tsx
  src/pages/MyPage.tsx
  src/pages/PlacePage.tsx
  src/pages/ReviewPage.tsx
  src/pages/VisitedPage.tsx
  src/shared/hooks/useBottomSheetDrag.ts
  src/shared/ui/BottomSheet/BottomSheet.tsx
  src/shared/ui/index.ts
  src/widgets/Header/index.ts
  src/widgets/Header/model/types.ts
  src/widgets/Header/ui/BackHeader.tsx
  src/widgets/Header/ui/CloseHeader.tsx
  src/widgets/Header/ui/MapHeader.tsx
  src/widgets/Header/ui/PlainHeader.tsx
Labels: 🔨 fix, 🛠 refactor

#74 [feat] : 링크로 들어온 사용차 처리
  src/pages/HistoryPage.tsx
  src/pages/MapViewPage.tsx
Labels: ✨ feature

#77 [fix] : kakaoLogin utils 분리
  src/features/main/ui/KakaoLogin.tsx
  src/features/mapView/ui/LoginModal.tsx
  src/shared/utils/index.ts
  src/shared/utils/kakaoLogin.ts
Labels: 🐞 bug, 🔨 fix

#78 [fix] : eventId 로컬 저장
  src/pages/HistoryPage.tsx
  src/pages/MapViewPage.tsx
Labels: 🐞 bug, 🔨 fix

#80 [feat] : 모임 생성자 추가 반영
  src/features/mapView/ui/BottomSheetContent.tsx
  src/shared/model/event.type.ts
Labels: ✨ feature

#82 [refactor] : 코드 리팩토링
  src/app/routes/routes.tsx
  src/features/find/ui/FindContainer.tsx
  src/features/find/ui/LocationStep.tsx
  src/features/find/ui/NameStep.tsx
  src/features/history/hooks/useUserInfo.ts
  src/features/history/service/api.ts
  src/features/history/ui/Banner.tsx
  src/features/history/ui/Chip.tsx
  src/features/history/ui/Header.tsx
  src/features/history/ui/PolicyBottomSheet.tsx
  src/features/history/ui/index.ts
  src/features/main/ui/KakaoLogin.tsx
  src/features/mapView/config/index.ts
  src/features/my/service/api.ts
  src/features/my/ui/Profile.tsx
  src/pages/HistoryPage.tsx
  src/pages/MainPage.tsx
  src/pages/MapViewPage.tsx
  src/pages/MyPage.tsx
  src/pages/PlacePage.tsx
  src/pages/ReviewPage.tsx
  src/pages/StartPointPage.tsx
  src/pages/VisitedPage.tsx
  src/shared/stores/userStore.ts
  src/widgets/headers/index.ts
  src/widgets/headers/model/types.ts
  src/widgets/headers/ui/BackHeader.tsx
  src/widgets/headers/ui/CloseHeader.tsx
  src/widgets/headers/ui/MapHeader.tsx
  src/widgets/headers/ui/PlainHeader.tsx
Labels: 🛠 refactor

#87 [refactor] : 아이콘 크기 지정
  src/features/detail/ui/Empty.tsx
  src/features/detail/ui/PlaceInfo.tsx
  src/features/find/ui/LocationStep.tsx
  src/features/history/ui/Banner.tsx
  src/features/history/ui/CheckBox.tsx
  src/features/history/ui/Chip.tsx
  src/features/history/ui/Empty.tsx
  src/features/history/ui/GroupCard.tsx
  src/features/mapView/ui/AddMemberBottomSheet.tsx
  src/features/mapView/ui/BackButton.tsx
  src/features/mapView/ui/BottomSheetContent.tsx
  src/features/mapView/ui/DetailBottomSheet/BusPath.tsx
  src/features/mapView/ui/DetailBottomSheet/FixedButton.tsx
  src/features/mapView/ui/DetailBottomSheet/Path.tsx
  src/features/mapView/ui/DetailBottomSheet/SubwayPath.tsx
  src/features/mapView/ui/DetailBottomSheet/TransferDetail.tsx
  src/features/mapView/ui/DetailBottomSheet/WalkPath.tsx
  src/features/mapView/ui/TooCloseSheet.tsx
  src/features/mapView/ui/TransferDetail.tsx
  src/features/mapView/ui/UserCard.tsx
  src/features/my/ui/Logout.tsx
  src/features/my/ui/Menu.tsx
  src/features/my/ui/Profile.tsx
  src/features/place/ui/ConfirmedCard.tsx
  src/features/place/ui/FilterChips.tsx
  src/features/place/ui/RecommendCard.tsx
  src/features/visited/ui/ScoreSelector.tsx
  src/pages/MainPage.tsx
  src/shared/ui/BottomSheet/Header.tsx
  src/shared/ui/InputField.tsx
  src/shared/ui/PlaceChip.tsx
  src/shared/ui/ShareModal.tsx
  src/widgets/headers/ui/BackHeader.tsx
  src/widgets/headers/ui/CloseHeader.tsx
  src/widgets/headers/ui/MapHeader.tsx
  src/widgets/headers/ui/PlainHeader.tsx
Labels: 🛠 refactor

#89 [feat] : 지하철 노선 chip 구현
  src/features/history/ui/Header.tsx
  src/features/mapView/config/subwayLine.ts
  src/features/mapView/ui/DetailBottomSheet/SubwayPath.tsx
  src/features/mapView/ui/MapDetailBottomSheet.tsx
  tailwind.config.cjs
Labels: ✨ feature, 🔨 fix, 💄 ui

#91 [feat] : MY 페이지 이름 수정 버튼 구현
  src/features/my/ui/Profile.tsx
Labels: ✨ feature, 💄 ui

#93 [hotfix] : history 리다이렉트 수정
  src/pages/HistoryPage.tsx
Labels: 🐞 bug, 🔨 fix

#99 [hotfix] : 마이페이지 렌더링 안되는 문제 해결
  src/features/find/ui/FindContainer.tsx
  src/features/history/ui/Header.tsx
  src/features/my/ui/Profile.tsx
  src/pages/HistoryPage.tsx
  src/pages/MyPage.tsx
  src/shared/stores/userStore.ts
  src/widgets/headers/ui/PlainHeader.tsx
Labels: 🐞 bug, 🔥 hot fix!!

#102 [fix] : 디자인과 일치하지 않는 ui 수정
  src/features/mapView/ui/BottomSheetContent.tsx
  src/shared/ui/ShareModal.tsx
Labels: 🔥 hot fix!!, 💄 ui

#104 [feat] : DE 페이지 UI 추가 구현
  public/image/KT3.webp
  src/assets/icon/whiteBack.svg
  src/assets/icon/whiteShare.svg
  src/features/detail/ui/PlaceInfo.tsx
  src/features/mapView/ui/DetailBottomSheet/MapButton.tsx
  src/features/mapView/ui/DetailBottomSheet/TransferDetail.tsx
  src/features/mapView/utils/kakaoMap.ts
  src/features/mapView/utils/tMap.ts
  src/pages/DetailPage.tsx
  src/widgets/headers/index.ts
  src/widgets/headers/ui/DetailHeader.tsx
Labels: 🛠 refactor, 💄 ui

#106 [fix] : qa 디자인 수정 사항 반영
  src/assets/icon/drag.svg
  src/features/history/ui/PolicyBottomSheet.tsx
  src/features/mapView/config/subwayLine.ts
  src/features/mapView/ui/AddMemberBottomSheet.tsx
  src/features/mapView/ui/BackButton.tsx
  src/features/mapView/ui/BottomSheetContent.tsx
  src/features/mapView/ui/KakaoMapView.tsx
  src/features/mapView/ui/MapMarker.tsx
  src/features/mapView/ui/MeetingMarker.tsx
  src/features/mapView/ui/SnapBottomSheet.tsx
  src/features/mapView/ui/TooCloseSheet.tsx
  src/features/mapView/ui/UserCard.tsx
  src/shared/ui/BottomSheet/BottomSheet.tsx
  src/shared/ui/BottomSheet/Header.tsx
  src/shared/ui/Modal.tsx
  src/shared/ui/PlaceCard.tsx
  src/shared/ui/SnapBottomSheet/SnapHeader.tsx
  src/shared/ui/SnapBottomSheet/SnapWrapper.tsx
  tailwind.config.cjs
Labels: 🐞 bug, 🔨 fix, 💄 ui

#108 [fix] : history 리다이렉트 문제
  src/features/mapView/ui/BottomSheetContent.tsx
  src/features/mapView/ui/LoginModal.tsx
  src/pages/MapViewPage.tsx
Labels: 🐞 bug, 🔨 fix

#111 [feat] : mp폴더 구조 세분화 및 기본 지도 이미지 추가
  src/assets/image/map.webp
  src/features/mapView/ui/bottomsheets/AddMemberBottomSheet.tsx
  src/features/mapView/ui/bottomsheets/MapDetailBottomSheet.tsx
  src/features/mapView/ui/bottomsheets/SnapBottomSheet.tsx
  src/features/mapView/ui/bottomsheets/TooCloseSheet.tsx
  src/features/mapView/ui/bottomsheets/detailContents/BusChip.tsx
  src/features/mapView/ui/bottomsheets/detailContents/BusPath.tsx
  src/features/mapView/ui/bottomsheets/detailContents/CarDetail.tsx
  src/features/mapView/ui/bottomsheets/detailContents/FixedButton.tsx
  src/features/mapView/ui/bottomsheets/detailContents/MapButton.tsx
  src/features/mapView/ui/bottomsheets/detailContents/Path.tsx
  src/features/mapView/ui/bottomsheets/detailContents/SubwayPath.tsx
  src/features/mapView/ui/bottomsheets/detailContents/TransferDetail.tsx
  src/features/mapView/ui/bottomsheets/detailContents/WalkPath.tsx
  src/features/mapView/ui/bottomsheets/detailContents/index.ts
  src/features/mapView/ui/bottomsheets/durationBottomsheet/BottomSheetContent.tsx
  src/features/mapView/ui/bottomsheets/durationBottomsheet/UserCard.tsx
  src/features/mapView/ui/bottomsheets/durationBottomsheet/index.ts
  src/features/mapView/ui/bottomsheets/index.ts
  src/features/mapView/ui/common/BackButton.tsx
  src/features/mapView/ui/common/LoginModal.tsx
  src/features/mapView/ui/common/index.ts
  src/features/mapView/ui/index.ts
  src/features/mapView/ui/map/DefaultMap.tsx
  src/features/mapView/ui/map/DetailKakaoMapView.tsx
  src/features/mapView/ui/map/KakaoMapView.tsx
  src/features/mapView/ui/map/MapMarker.tsx
  src/features/mapView/ui/map/MeetingMarker.tsx
  src/features/mapView/ui/map/index.ts
  src/pages/MapViewPage.tsx
Labels: ✨ feature, 🛠 refactor

#110 [fix] : zustand 새로고침 시 값 사라지는 문제 해결
  src/features/my/hooks/useLogout.ts
  src/shared/stores/userStore.ts
Labels: 🐞 bug, 🔨 fix

#114 [fix] : 중간 마커 우선순위 높이기
  src/assets/icon/addDisabled.svg
  src/features/mapView/ui/bottomsheets/durationBottomsheet/BottomSheetContent.tsx
  src/features/mapView/ui/map/MeetingMarker.tsx
  src/shared/model/kakao.maps.d.ts
Labels: 🐞 bug, 🔨 fix

#115 [feat] : HI 페이지 모임 만들기 UI 수정 적용
  src/assets/icon/arrow.svg
  src/assets/image/banner.webp
  src/features/history/ui/Banner.tsx
  src/features/history/ui/Header.tsx
  src/features/history/ui/index.ts
  src/pages/HistoryPage.tsx
  src/shared/model/mocks/mockListData.ts
Labels: ✨ feature, 💄 ui

#121 [fix] : 스크롤 끝까지 안되는 문제 해결
  src/features/visited/ui/SecondStep.tsx
  src/pages/DetailPage.tsx
Labels: 🐞 bug, 🔨 fix

#123 [feat] : 주차장 표시 아이콘 변경
  src/assets/icon/parking.svg
Labels: 💄 ui

#125 [feat] : pl 응답값에 맞게 props 정리
  src/features/detail/config/TagTypeInfo.ts
  src/features/place/model/index.ts
  src/features/place/model/placeList.type.ts
  src/features/place/ui/ConfirmedCard.tsx
  src/features/place/ui/RecommendList.tsx
  src/pages/PlacePage.tsx
  src/pages/ReviewPage.tsx
  src/shared/model/index.ts
  src/shared/model/mocks/mockPlaceItems.ts
  src/shared/model/mocks/mockPlaceList.ts
  src/shared/model/score.type.ts
  src/shared/ui/PlaceCard.tsx
  src/shared/ui/PlaceChip.tsx
  src/shared/utils/formatReview.ts
  src/shared/utils/index.ts
Labels: ✨ feature, 🔨 fix

#127 [feat] 유저 모임 리스트 get 요청 API 연결
  src/features/history/hooks/index.ts
  src/features/history/hooks/useUserEvents.ts
  src/features/history/model/index.ts
  src/features/history/model/userEvents.type.ts
  src/features/history/service/api.ts
  src/features/history/ui/Chip.tsx
  src/features/history/ui/GroupCard.tsx
  src/pages/HistoryPage.tsx
Labels: ⚙ api, ✨ feature

#129 [feat] : HI 페이지 수정 사항 반영
  src/app/routes/routes.tsx
  src/features/find/hooks/useCreateStartPoint.ts
  src/features/history/ui/GroupCard.tsx
  src/features/mapView/hooks/useEventInfo.ts
  src/features/mapView/hooks/useTransfer.ts
  src/features/mapView/ui/bottomsheets/durationBottomsheet/BottomSheetContent.tsx
  src/features/mapView/ui/common/LoginModal.tsx
Labels: 🔨 fix, 💄 ui

#133 [feat] : place페이지 api 연결
  src/app/routes/routes.tsx
  src/features/mapView/ui/bottomsheets/SnapBottomSheet.tsx
  src/features/place/hooks/index.ts
  src/features/place/hooks/useRecommendedPlaces.ts
  src/features/place/model/placeList.type.ts
  src/features/place/service/api.ts
  src/features/place/service/index.ts
  src/features/place/ui/RecommendCard.tsx
  src/features/place/ui/RecommendList.tsx
  src/pages/PlacePage.tsx
  src/shared/model/mocks/mockPlaceItems.ts
Labels: ⚙ api, ✨ feature

#132 [feat] : 서비스 약관 페이지 UI 구현
  src/app/routes/routes.tsx
  src/features/history/ui/CheckBox.tsx
  src/features/history/ui/PolicyBottomSheet.tsx
  src/features/my/ui/Menu.tsx
  src/pages/MarketingPage.tsx
  src/pages/PolicyPage.tsx
  src/widgets/headers/ui/CloseHeader.tsx
Labels: 💄 ui

#136 [feat] : DE api 연결
  public/image/KT4.webp
  src/features/detail/hooks/index.ts
  src/features/detail/hooks/usePlaceInfo.ts
  src/features/detail/hooks/useSetPlace.ts
  src/features/detail/model/index.ts
  src/features/detail/model/place.type.ts
  src/features/detail/service/api.ts
  src/features/detail/service/index.ts
  src/features/detail/ui/PlaceButton.tsx
  src/features/detail/ui/PlaceInfo.tsx
  src/features/detail/ui/Review.tsx
  src/features/detail/ui/ReviewItem.tsx
  src/features/detail/ui/index.ts
  src/features/place/ui/RecommendList.tsx
  src/pages/DetailPage.tsx
  src/pages/MapViewPage.tsx
  src/shared/utils/index.ts
  src/shared/utils/toValidScore.ts
  src/widgets/headers/ui/DetailHeader.tsx
Labels: ⚙ api, ✨ feature, 💄 ui

#139 [refactor] : service, hooks 로직 분리 및 리팩토링
  src/features/detail/service/api.ts
  src/features/find/service/api.ts
  src/features/history/service/api.ts
  src/features/mapView/service/api.ts
  src/features/my/service/api.ts
  src/features/place/service/api.ts
Labels: 🛠 refactor

#142 [feat] : 로딩스피너 및 토스트팝업 구현
  src/pages/DetailPage.tsx
  src/pages/HistoryPage.tsx
  src/pages/MapViewPage.tsx
  src/pages/PlacePage.tsx
  src/pages/ReviewPage.tsx
  src/shared/ui/LoadingSpinner.tsx
  src/shared/ui/ShareModal.tsx
  src/shared/ui/Toast.tsx
  src/shared/ui/index.ts
Labels: ✨ feature

#144 [feat] : 자가용, 대중교통 상세 경로 표시
  src/features/mapView/ui/bottomsheets/MapDetailBottomSheet.tsx
  src/features/mapView/ui/map/DetailKakaoMapView.tsx
  src/features/mapView/ui/map/ParkingMarker.tsx
  src/pages/MapViewPage.tsx
  src/shared/model/event.type.ts
Labels: ⚙ api, ✨ feature, 💄 ui

#148 [feat] : HI 무한스크롤 적용 및 401 에러 처리
  src/features/history/hooks/useUserEvents.ts
  src/features/history/model/userEvents.type.ts
  src/features/history/service/api.ts
  src/features/history/ui/GroupCard.tsx
  src/features/history/utils/formatDaysAgo.ts
  src/features/history/utils/index.ts
  src/pages/HistoryPage.tsx
  src/shared/api/api.ts
Labels: ⚙ api, ✨ feature

#147 [feat] : guestId로 교체
  src/features/find/hooks/useCreateStartPoint.ts
  src/features/mapView/hooks/useEventInfo.ts
  src/features/mapView/service/api.ts
  src/pages/MapViewPage.tsx
Labels: ⚙ api, ✨ feature

#150 [feat] : jest 테스트 함수 구현
  jest.config.ts
  package.json
  pnpm-lock.yaml
  src/features/history/utils/formatDaysAgo.test.ts
  src/features/history/utils/formatDaysAgo.ts
  src/shared/utils/toValidScore.test.ts
  tsconfig.app.json
  tsconfig.json
Labels: ✨ feature

#152 [feat] : validateName 및 formatReview 테스트 코드 작성
  src/shared/utils/formatReview.test.ts
  src/shared/utils/validateName.test.ts
Labels: ✨ feature

#155 [fix] #noissue : Rename formatName.test.ts to formatName.test.ts
  src/shared/utils/formatName.test.ts
Labels: 🐞 bug, 🔨 fix

#167 [fix] : QA 디자인 수정 사항 반영
  src/assets/icon/afternoon.svg
  src/assets/icon/afternoonBlue.svg
  src/assets/icon/evening.svg
  src/assets/icon/eveningBlue.svg
  src/assets/icon/morning.svg
  src/assets/icon/morningBlue.svg
  src/assets/image/afternoon.webp
  src/assets/image/afternoonBlue.webp
  src/assets/image/evening.webp
  src/assets/image/eveningBlue.webp
  src/assets/image/morning.webp
  src/assets/image/morningBlue.webp
  src/features/mapView/ui/bottomsheets/detailContents/Path.tsx
  src/features/mapView/ui/bottomsheets/durationBottomsheet/BottomSheetContent.tsx
  src/features/mapView/ui/common/BackButton.tsx
  src/features/review/ui/Title.tsx
  src/features/visited/ui/FirstStep.tsx
  src/pages/DetailPage.tsx
  src/pages/HistoryPage.tsx
  src/pages/ReviewPage.tsx
Labels: 🐞 bug, ✨ feature, 🔨 fix, 💄 ui

#168 [fix] : FI와 RE QA수정사항 반영
  src/entities/place/hooks/useSearch.ts
  src/features/find/service/coord2Address.ts
  src/features/find/ui/GetLocationButton.tsx
  src/features/find/ui/LocationStep.tsx
  src/features/notVisited/ui/CompleteButton.tsx
  src/features/notVisited/ui/OtherPlaceForm.tsx
  src/features/notVisited/ui/PlaceSearch.tsx
Labels: 🐞 bug, 🔨 fix

#174 [feat] : kt 에러 핸들링 추가
  src/shared/utils/kakaoShare.ts
Labels: 🐞 bug, 🔨 fix

#180 [fix] : RE 페이지 버그 수정
  src/app/routes/routes.tsx
  src/features/notVisited/hooks/useNonVisitedReview.ts
  src/features/notVisited/service/api.ts
  src/features/review/ui/SmallButton.tsx
  src/features/visited/hooks/useVisitedReview.ts
  src/features/visited/service/api.ts
  src/pages/NotVisitedPage.tsx
  src/pages/ReviewPage.tsx
  src/pages/VisitedPage.tsx
Labels: ⚙ api, 🐞 bug, 🔨 fix
